import type { FillType, FontId, ShapeKind, SymbolId } from '../model/types';

export type Palette = readonly [string, string];

/** A subject the user can describe: a role, a job, a vibe, a thing. */
export interface Theme {
  id: string;
  /** Suggested role name. */
  label: string;
  keywords: readonly string[];
  emoji: readonly string[];
  symbols: readonly SymbolId[];
  palettes: readonly Palette[];
  shapes: readonly ShapeKind[];
  /** Color for symbols, text and the border when set (e.g. neon green on a dark developer icon). */
  contentColor?: string;
  gloss?: boolean;
  border?: boolean;
  /** Finishes the sentence "For <label> I picked …". */
  reason: string;
}

/** An adjective that changes the look rather than the subject. */
export interface Style {
  id: string;
  label: string;
  keywords: readonly string[];
  palettes?: readonly Palette[];
  shapes?: readonly ShapeKind[];
  fillType?: FillType;
  border?: boolean;
  gloss?: boolean;
  shadow?: boolean;
  /** Colored glow instead of a plain drop shadow. */
  glow?: boolean;
  contentShadow?: boolean;
  font?: FontId;
  prefer?: 'emoji' | 'symbol';
  emoji?: readonly string[];
  symbols?: readonly SymbolId[];
  contentColor?: string;
}

export const COLOR_WORDS: Readonly<Record<string, string>> = {
  red: '#e74c3c',
  crimson: '#b3121b',
  scarlet: '#ff2e2e',
  maroon: '#800000',
  ruby: '#c0143c',
  orange: '#e67e22',
  amber: '#f0b232',
  peach: '#ffb385',
  coral: '#ff7f50',
  yellow: '#f1c40f',
  gold: '#f1c40f',
  golden: '#f1c40f',
  lemon: '#ffe34d',
  lime: '#8bec3b',
  green: '#2ecc71',
  emerald: '#1f8b4c',
  mint: '#7fe7c4',
  olive: '#7a8b2b',
  forest: '#1f5f3a',
  teal: '#1abc9c',
  turquoise: '#1abc9c',
  aqua: '#00d4ff',
  cyan: '#00d4ff',
  sky: '#5dc7ff',
  blue: '#3498db',
  navy: '#1b3b6f',
  indigo: '#4b3fbf',
  azure: '#2f80ed',
  purple: '#9b59b6',
  violet: '#7d3cff',
  lavender: '#b39ddb',
  lilac: '#c8a2ff',
  magenta: '#e91e63',
  pink: '#ff73fa',
  rose: '#ff5c8a',
  fuchsia: '#ff2fb3',
  hotpink: '#ff1493',
  brown: '#8d5a3b',
  chocolate: '#5c3a21',
  beige: '#e8d8b8',
  cream: '#fff4d6',
  tan: '#d2b48c',
  black: '#1e1f22',
  charcoal: '#2b2d31',
  gray: '#95a5a6',
  grey: '#95a5a6',
  silver: '#c0c7cc',
  white: '#f2f3f5',
  blurple: '#5865f2',
};

/** Words that darken or lighten the color word right after them. */
export const COLOR_MODIFIERS: Readonly<Record<string, number>> = {
  dark: 0.3,
  deep: 0.3,
  darker: 0.3,
  midnight: 0.45,
  light: -0.25,
  pale: -0.35,
  pastel: -0.4,
  soft: -0.25,
  bright: -0.08,
  vivid: -0.05,
  hot: -0.05,
  electric: -0.05,
  ice: -0.3,
  baby: -0.35,
  royal: 0.15,
  ocean: 0.1,
  cherry: 0.1,
  burnt: 0.35,
  blood: 0.35,
  wine: 0.4,
};

/** Unambiguous shape words. */
export const SHAPE_WORDS: Readonly<Record<string, ShapeKind>> = {
  circle: 'circle',
  circular: 'circle',
  round: 'circle',
  square: 'square',
  boxy: 'square',
  rounded: 'roundedSquare',
  squircle: 'squircle',
  hexagon: 'hexagon',
  hexagonal: 'hexagon',
  hex: 'hexagon',
  badge: 'badge',
  seal: 'badge',
  scalloped: 'badge',
  rosette: 'badge',
};

/** Words that are a shape only when the user says "shape", "background" etc. next to them. */
export const AMBIGUOUS_SHAPE_WORDS: Readonly<Record<string, ShapeKind>> = {
  shield: 'shield',
  star: 'star',
  heart: 'heart',
  diamond: 'diamond',
  rhombus: 'diamond',
};

export const SHAPE_CONTEXT_WORDS: readonly string[] = [
  'shape',
  'shaped',
  'background',
  'backdrop',
  'outline',
  'frame',
  'base',
  'plate',
];

export const THEMES: readonly Theme[] = [
  {
    id: 'admin',
    label: 'Admin',
    keywords: ['admin', 'administrator', 'crown', 'owner', 'manager', 'managers', 'management', 'director', 'executive', 'supervisor', 'lead', 'leads', 'coordinator', 'president', 'coowner', 'co-owner', 'founder', 'leader', 'king', 'queen', 'boss', 'ceo', 'chief', 'royal', 'royalty', 'ruler', 'emperor', 'empress', 'monarch', 'prince', 'princess', 'head'],
    emoji: ['👑', '🫅', '🏰'],
    symbols: ['crown'],
    palettes: [['#ff5f5f', '#b3121b'], ['#f1c40f', '#e67e22'], ['#9b59b6', '#71368a']],
    shapes: ['shield', 'badge', 'circle'],
    gloss: true,
    border: true,
    reason: 'a crown, because they run the place',
  },
  {
    id: 'moderator',
    label: 'Moderator',
    keywords: ['mod', 'moderator', 'moderation', 'staff', 'helper', 'support', 'guardian', 'guard', 'protector', 'sheriff', 'warden', 'security', 'sentinel', 'trial mod', 'junior mod', 'senior mod', 'head mod'],
    emoji: ['🛡️', '👮', '⚖️'],
    symbols: ['shield', 'check'],
    palettes: [['#2ecc71', '#1f8b4c'], ['#3498db', '#206694'], ['#1abc9c', '#11806a']],
    shapes: ['circle', 'shield', 'roundedSquare'],
    border: true,
    reason: 'a shield, because they keep the server safe',
  },
  {
    id: 'vip',
    label: 'VIP',
    keywords: ['vip', 'premium', 'elite', 'exclusive', 'luxury', 'deluxe', 'platinum', 'patron', 'sponsor', 'donor', 'donator', 'supporter', 'subscriber', 'sub', 'subs', 'tier', 'og'],
    emoji: ['💎', '⭐', '🌟'],
    symbols: ['gem', 'star'],
    palettes: [['#f1c40f', '#e67e22'], ['#ffd166', '#c27c0e'], ['#ff73fa', '#b845c1']],
    shapes: ['roundedSquare', 'badge', 'circle'],
    gloss: true,
    reason: 'gold and a gem, because it should feel exclusive',
  },
  {
    id: 'booster',
    label: 'Server Booster',
    keywords: ['booster', 'boosters', 'boost', 'boosting', 'boosted', 'nitro'],
    emoji: ['💎', '🚀', '✨'],
    symbols: ['gem'],
    palettes: [['#ff73fa', '#b845c1'], ['#f47fff', '#71368a']],
    shapes: ['circle', 'star', 'badge'],
    reason: "a gem in Discord's boost pink",
  },
  {
    id: 'bot',
    label: 'Bot',
    keywords: ['bot', 'bots', 'robot', 'robots', 'automation', 'automated', 'ai', 'assistant', 'android', 'cyborg', 'machine'],
    emoji: ['🤖', '⚙️', '🔌'],
    symbols: ['gear'],
    palettes: [['#3498db', '#206694'], ['#95a5a6', '#546e7a'], ['#00d4ff', '#0066ff']],
    shapes: ['roundedSquare', 'square', 'hexagon'],
    reason: 'a robot face on a squared-off tile',
  },
  {
    id: 'verified',
    label: 'Verified',
    keywords: ['verified', 'official', 'trusted', 'approved', 'checked', 'legit', 'authentic', 'certified', 'confirmed', 'vetted'],
    emoji: ['✅', '☑️'],
    symbols: ['check'],
    palettes: [['#3498db', '#206694'], ['#2ecc71', '#1f8b4c']],
    shapes: ['badge', 'circle'],
    reason: 'a check mark on a scalloped badge, like a verification tick',
  },
  {
    id: 'artist',
    label: 'Artist',
    keywords: ['artist', 'artists', 'art', 'arts', 'drawing', 'draw', 'painter', 'painting', 'illustrator', 'illustration', 'designer', 'design', 'creative', 'creator', 'sketch', 'sketching', 'doodle', 'animator', 'animation'],
    emoji: ['🎨', '🖌️', '✏️'],
    symbols: [],
    palettes: [['#9b59b6', '#e91e63'], ['#e91e63', '#e67e22'], ['#1abc9c', '#9b59b6']],
    shapes: ['circle', 'roundedSquare', 'squircle'],
    reason: 'a palette on a colorful gradient',
  },
  {
    id: 'gamer',
    label: 'Gamer',
    keywords: ['gamer', 'gamers', 'gaming', 'game', 'games', 'player', 'players', 'controller', 'console', 'esports', 'esport', 'minecraft', 'fortnite', 'valorant', 'roblox', 'league', 'lol', 'csgo', 'cs2', 'apex', 'overwatch', 'among us', 'speedrun', 'speedrunner', 'pro', 'noob', 'squad'],
    emoji: ['🎮', '🕹️', '👾', '🎯'],
    symbols: ['bolt'],
    palettes: [['#1abc9c', '#206694'], ['#9b59b6', '#3498db'], ['#e74c3c', '#71368a']],
    shapes: ['hexagon', 'roundedSquare', 'shield'],
    reason: 'a controller on a hexagon, the classic gaming look',
  },
  {
    id: 'developer',
    label: 'Developer',
    keywords: ['developer', 'developers', 'dev', 'devs', 'coder', 'coders', 'coding', 'code', 'programmer', 'programming', 'engineer', 'engineering', 'software', 'hacker', 'script', 'scripter', 'scripting', 'webdev', 'backend', 'frontend', 'fullstack', 'python', 'javascript', 'typescript', 'rust', 'java'],
    emoji: ['💻', '🖥️', '⌨️'],
    symbols: ['code', 'gear'],
    palettes: [['#1e1f22', '#3f4147'], ['#2b2d31', '#111214'], ['#206694', '#0f2a44']],
    shapes: ['roundedSquare', 'square'],
    contentColor: '#2ecc71',
    border: true,
    reason: 'code brackets in terminal green on a dark tile',
  },
  {
    id: 'streamer',
    label: 'Streamer',
    keywords: ['streamer', 'streamers', 'stream', 'streaming', 'live', 'twitch', 'youtube', 'youtuber', 'tiktok', 'tiktoker', 'influencer', 'broadcast', 'broadcaster', 'vtuber', 'partner', 'affiliate'],
    emoji: ['🎥', '📺', '🎙️', '🔴'],
    symbols: ['bolt'],
    palettes: [['#e91e63', '#71368a'], ['#8e44ad', '#71368a'], ['#e74c3c', '#992d22']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a camera on a purple-to-magenta gradient, very "live"',
  },
  {
    id: 'music',
    label: 'Music',
    keywords: ['music', 'musician', 'dj', 'singer', 'song', 'songs', 'band', 'audio', 'sound', 'beats', 'producer', 'rapper', 'karaoke', 'guitarist', 'drummer', 'pianist', 'vocalist', 'composer', 'melody', 'playlist'],
    emoji: ['🎵', '🎶', '🎧', '🎸', '🎤', '🎹'],
    symbols: ['note'],
    palettes: [['#11806a', '#1abc9c'], ['#9b59b6', '#3498db'], ['#e91e63', '#9b59b6']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a music note, naturally',
  },
  {
    id: 'night',
    label: 'Night Owl',
    keywords: ['night', 'nocturnal', 'moon', 'owl', 'owls', 'midnight', 'sleep', 'sleepy', 'insomniac', 'insomnia', 'lunar', 'nightowl', 'dusk', 'twilight'],
    emoji: ['🌙', '🦉', '✨', '🌌'],
    symbols: ['moon'],
    palettes: [['#206694', '#0f2a44'], ['#71368a', '#0f2a44'], ['#2b2d31', '#111214']],
    shapes: ['circle', 'roundedSquare'],
    contentColor: '#f1c40f',
    reason: 'a golden moon on a midnight blue',
  },
  {
    id: 'fire',
    label: 'Fire',
    keywords: ['fire', 'flame', 'flames', 'hot', 'burn', 'burning', 'lit', 'blaze', 'inferno', 'lava', 'pyro', 'heat', 'ember', 'phoenix'],
    emoji: ['🔥', '🌋', '🐉'],
    symbols: ['flame'],
    palettes: [['#ff5f5f', '#b3121b'], ['#e67e22', '#992d22'], ['#f1c40f', '#e74c3c']],
    shapes: ['circle', 'hexagon', 'shield'],
    reason: 'flames in red and orange',
  },
  {
    id: 'star',
    label: 'Star',
    keywords: ['star', 'stars', 'starry', 'celebrity', 'famous', 'legend', 'legendary', 'hero', 'heroes', 'mvp', 'allstar', 'superstar', 'rising', 'icon', 'iconic', 'notable', 'featured', 'spotlight'],
    emoji: ['⭐', '🌟', '✨', '💫'],
    symbols: ['star'],
    palettes: [['#f1c40f', '#e67e22'], ['#3498db', '#206694'], ['#9b59b6', '#71368a']],
    shapes: ['circle', 'badge', 'roundedSquare'],
    reason: 'a star, for someone who stands out',
  },
  {
    id: 'love',
    label: 'Sweetheart',
    keywords: ['love', 'lover', 'heart', 'hearts', 'kind', 'kindness', 'friendly', 'friend', 'friends', 'friendship', 'caring', 'care', 'sweetheart', 'couple', 'couples', 'dating', 'romance', 'romantic', 'valentine', 'crush', 'simp', 'wholesome', 'hug', 'hugs', 'bestie', 'besties'],
    emoji: ['❤️', '💖', '💕', '💗', '🫶'],
    symbols: ['heart'],
    palettes: [['#e91e63', '#ad1457'], ['#ff73fa', '#e91e63'], ['#ff8fa3', '#e91e63']],
    shapes: ['circle', 'heart', 'roundedSquare'],
    reason: 'hearts in pink',
  },
  {
    id: 'skull',
    label: 'Outlaw',
    keywords: ['skull', 'skulls', 'death', 'dead', 'deadly', 'undead', 'zombie', 'zombies', 'reaper', 'grim', 'pirate', 'pirates', 'poison', 'toxic', 'danger', 'dangerous', 'killer', 'assassin', 'villain', 'villains', 'evil', 'demon', 'demons', 'devil', 'outlaw', 'rebel', 'rebels', 'bandit', 'goth', 'metal'],
    emoji: ['💀', '☠️', '🏴‍☠️', '😈', '👿'],
    symbols: ['skull'],
    palettes: [['#2b2d31', '#111214'], ['#992d22', '#111214'], ['#71368a', '#111214']],
    shapes: ['circle', 'shield', 'hexagon'],
    contentColor: '#f2f3f5',
    reason: 'a skull on near-black',
  },
  {
    id: 'warrior',
    label: 'Warrior',
    keywords: ['warrior', 'warriors', 'knight', 'knights', 'fighter', 'fighters', 'fight', 'pvp', 'battle', 'war', 'army', 'soldier', 'soldiers', 'military', 'sword', 'swords', 'blade', 'samurai', 'ninja', 'viking', 'vikings', 'gladiator', 'raid', 'raider', 'raiders', 'clan', 'guild', 'crusader', 'paladin', 'berserker', 'tank', 'dps'],
    emoji: ['⚔️', '🗡️', '🛡️', '🥷', '🏹'],
    symbols: ['sword', 'shield'],
    palettes: [['#95a5a6', '#546e7a'], ['#992d22', '#2b2d31'], ['#3498db', '#206694']],
    shapes: ['shield', 'hexagon', 'badge'],
    border: true,
    reason: 'crossed steel on a shield',
  },
  {
    id: 'key',
    label: 'Keyholder',
    keywords: ['key', 'keys', 'access', 'vault', 'unlock', 'locked', 'lock', 'secret', 'secrets', 'password', 'gatekeeper', 'doorman', 'bouncer', 'entry', 'backstage', 'insider', 'private'],
    emoji: ['🔑', '🗝️', '🔒', '🔓'],
    symbols: ['key'],
    palettes: [['#f1c40f', '#c27c0e'], ['#546e7a', '#2b2d31'], ['#e67e22', '#a84300']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a key, for access',
  },
  {
    id: 'champion',
    label: 'Champion',
    keywords: ['champion', 'champions', 'winner', 'winners', 'win', 'wins', 'trophy', 'tournament', 'tourney', 'victory', 'victor', '1st', 'first place', 'best', 'goat', 'ranked', 'rank', 'leaderboard', 'medal', 'podium', 'contest', 'competition', 'competitive'],
    emoji: ['🏆', '🥇', '🏅', '🎖️'],
    symbols: ['trophy'],
    palettes: [['#f1c40f', '#e67e22'], ['#ffd166', '#c27c0e'], ['#3498db', '#206694']],
    shapes: ['circle', 'badge', 'shield'],
    gloss: true,
    reason: 'a trophy in gold',
  },
  {
    id: 'pets',
    label: 'Pet Lover',
    keywords: ['pet', 'pets', 'animal', 'animals', 'furry', 'furries', 'paw', 'paws', 'zoo', 'wildlife', 'vet'],
    emoji: ['🐾', '🐶', '🐱'],
    symbols: ['paw'],
    palettes: [['#e67e22', '#a84300'], ['#2ecc71', '#1f8b4c'], ['#ff73fa', '#b845c1']],
    shapes: ['circle', 'roundedSquare', 'heart'],
    reason: 'a paw print',
  },
  {
    id: 'builder',
    label: 'Builder',
    keywords: ['builder', 'builders', 'build', 'building', 'construction', 'architect', 'crafter', 'crafting', 'maker', 'makers', 'mechanic', 'repair', 'fixer', 'tinkerer', 'engineer', 'redstone', 'modder', 'modding', 'plugin', 'tech', 'technical'],
    emoji: ['🔨', '🔧', '🛠️', '⚙️', '🧱'],
    symbols: ['gear'],
    palettes: [['#e67e22', '#a84300'], ['#95a5a6', '#546e7a'], ['#f1c40f', '#c27c0e']],
    shapes: ['hexagon', 'roundedSquare', 'square'],
    reason: 'a gear for someone who builds things',
  },
  {
    id: 'energy',
    label: 'Energy',
    keywords: ['lightning', 'thunder', 'fast', 'speed', 'speedy', 'energy', 'power', 'powerful', 'electric', 'electricity', 'volt', 'shock', 'storm', 'flash', 'hyper', 'active', 'quick', 'rapid', 'turbo', 'nitro', 'zap'],
    emoji: ['⚡', '🌩️', '💥'],
    symbols: ['bolt'],
    palettes: [['#f1c40f', '#e67e22'], ['#00d4ff', '#0066ff'], ['#9b59b6', '#3498db']],
    shapes: ['circle', 'hexagon', 'diamond'],
    reason: 'a lightning bolt',
  },
  {
    id: 'newbie',
    label: 'Newcomer',
    keywords: ['newbie', 'newcomer', 'newcomers', 'beginner', 'beginners', 'rookie', 'rookies', 'starter', 'starters', 'trainee', 'apprentice', 'junior', 'level 1', 'unverified', 'visitor', 'visitors', 'guest', 'guests', 'welcome', 'welcomer', 'greeter'],
    emoji: ['🌱', '👋', '🐣', '🔰'],
    symbols: [],
    palettes: [['#2ecc71', '#1f8b4c'], ['#7fe7c4', '#1abc9c'], ['#3498db', '#206694']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a sprout, because they are just getting started',
  },
  {
    id: 'events',
    label: 'Event Host',
    keywords: ['event', 'events', 'host', 'hosts', 'hosting', 'party', 'parties', 'celebrate', 'celebration', 'confetti', 'hype', 'hyped', 'organizer', 'organiser', 'planner', 'giveaway', 'giveaways', 'raffle', 'birthday', 'festival', 'fest', 'fun'],
    emoji: ['🎉', '🥳', '🎊', '🎈', '🎁'],
    symbols: ['star'],
    palettes: [['#e91e63', '#e67e22'], ['#f1c40f', '#e91e63'], ['#9b59b6', '#e91e63']],
    shapes: ['circle', 'star', 'badge'],
    reason: 'confetti on a bright gradient',
  },
  {
    id: 'scholar',
    label: 'Scholar',
    keywords: ['book', 'books', 'reader', 'readers', 'reading', 'library', 'librarian', 'study', 'student', 'students', 'school', 'teacher', 'teachers', 'learn', 'learning', 'education', 'educator', 'class', 'tutor', 'mentor', 'mentors', 'professor', 'scholar', 'academic', 'smart', 'genius', 'brain', 'brainy', 'nerd', 'nerds', 'quiz', 'trivia', 'know', 'knowledge', 'wise', 'wisdom', 'sage', 'expert', 'experts', 'veteran', 'veterans'],
    emoji: ['📚', '🎓', '🧠', '📖', '🦉'],
    symbols: [],
    palettes: [['#3498db', '#206694'], ['#9b59b6', '#71368a'], ['#e67e22', '#a84300']],
    shapes: ['circle', 'roundedSquare', 'shield'],
    reason: 'books and a graduation cap',
  },
  {
    id: 'science',
    label: 'Scientist',
    keywords: ['science', 'scientist', 'lab', 'chemistry', 'chemist', 'physics', 'physicist', 'biology', 'biologist', 'dna', 'research', 'researcher', 'experiment', 'experiments', 'alchemist', 'alchemy', 'potion', 'potions', 'math', 'mathematics', 'mathematician', 'data', 'analyst'],
    emoji: ['🧪', '🔬', '🧬', '⚗️', '🔭'],
    symbols: ['gear'],
    palettes: [['#1abc9c', '#206694'], ['#2ecc71', '#11806a'], ['#9b59b6', '#3498db']],
    shapes: ['circle', 'hexagon', 'roundedSquare'],
    reason: 'a test tube on a hexagon (very molecule)',
  },
  {
    id: 'money',
    label: 'Trader',
    keywords: ['money', 'rich', 'cash', 'finance', 'financial', 'bank', 'banker', 'crypto', 'bitcoin', 'trader', 'trading', 'investor', 'investing', 'stocks', 'economy', 'economist', 'merchant', 'shop', 'shopkeeper', 'seller', 'vendor', 'store', 'market', 'business', 'entrepreneur', 'hustler', 'whale', 'wealthy', 'millionaire', 'coins', 'coin'],
    emoji: ['💰', '💵', '💸', '🪙', '📈'],
    symbols: ['gem'],
    palettes: [['#2ecc71', '#1f8b4c'], ['#f1c40f', '#c27c0e'], ['#11806a', '#1abc9c']],
    shapes: ['circle', 'roundedSquare', 'badge'],
    reason: 'a money bag in green and gold',
  },
  {
    id: 'space',
    label: 'Explorer',
    keywords: ['space', 'galaxy', 'cosmic', 'cosmos', 'astro', 'astronaut', 'rocket', 'launch', 'planet', 'planets', 'saturn', 'alien', 'aliens', 'ufo', 'nasa', 'orbit', 'universe', 'nebula', 'stellar', 'interstellar', 'explorer', 'explorers', 'explore', 'adventure', 'adventurer', 'traveler', 'traveller', 'travel', 'wanderer', 'nomad', 'pioneer'],
    emoji: ['🚀', '🪐', '👽', '🛸', '🧭', '🌌'],
    symbols: ['moon', 'star'],
    palettes: [['#71368a', '#0f2a44'], ['#206694', '#0f2a44'], ['#9b59b6', '#206694']],
    shapes: ['circle', 'hexagon'],
    reason: 'a rocket on a deep-space gradient',
  },
  {
    id: 'nature',
    label: 'Nature',
    keywords: ['nature', 'natural', 'eco', 'green', 'forest', 'forests', 'plant', 'plants', 'garden', 'gardener', 'gardening', 'tree', 'trees', 'leaf', 'leaves', 'flower', 'flowers', 'floral', 'blossom', 'sakura', 'earth', 'environment', 'environmental', 'outdoors', 'outdoor', 'hiking', 'hiker', 'camping', 'camper', 'farmer', 'farm', 'farming', 'druid', 'ranger'],
    emoji: ['🌿', '🌲', '🌸', '🍀', '🌻', '🌱'],
    symbols: [],
    palettes: [['#2ecc71', '#1f8b4c'], ['#11806a', '#1abc9c'], ['#7fe7c4', '#1f8b4c']],
    shapes: ['circle', 'roundedSquare', 'heart'],
    reason: 'leaves in fresh greens',
  },
  {
    id: 'ocean',
    label: 'Ocean',
    keywords: ['ocean', 'sea', 'water', 'wave', 'waves', 'surf', 'surfer', 'beach', 'island', 'marine', 'diver', 'diving', 'sailor', 'captain', 'navy', 'fish', 'fishing', 'fisher', 'shark', 'dolphin', 'whale', 'octopus', 'mermaid', 'aqua', 'lake', 'river', 'swim', 'swimmer', 'swimming', 'pool'],
    emoji: ['🌊', '🐬', '🐙', '🦈', '⚓', '🐳'],
    symbols: [],
    palettes: [['#1abc9c', '#206694'], ['#00d4ff', '#0066ff'], ['#3498db', '#0f2a44']],
    shapes: ['circle', 'squircle', 'roundedSquare'],
    reason: 'a wave in ocean blues',
  },
  {
    id: 'winter',
    label: 'Frost',
    keywords: ['snow', 'snowflake', 'ice', 'icy', 'frozen', 'frost', 'frosty', 'winter', 'cold', 'chilly', 'arctic', 'polar', 'penguin', 'penguins', 'christmas', 'xmas', 'holiday', 'holidays', 'festive', 'santa', 'elf'],
    emoji: ['❄️', '⛄', '🐧', '🎄', '🎅', '🧊'],
    symbols: ['star'],
    palettes: [['#a8e6ff', '#3498db'], ['#00d4ff', '#0066ff'], ['#f2f3f5', '#95a5a6']],
    shapes: ['circle', 'hexagon', 'badge'],
    contentColor: '#0f2a44',
    reason: 'a snowflake in icy blue',
  },
  {
    id: 'spooky',
    label: 'Spooky',
    keywords: ['spooky', 'scary', 'halloween', 'creepy', 'horror', 'haunted', 'ghost', 'ghosts', 'pumpkin', 'boo', 'vampire', 'vampires', 'witch', 'witches', 'werewolf', 'monster', 'monsters', 'nightmare', 'eerie', 'cursed', 'phantom', 'haunt'],
    emoji: ['👻', '🎃', '🧛', '🕸️', '🦇', '🧟'],
    symbols: ['skull'],
    palettes: [['#ff7a00', '#1e1f22'], ['#6a0dad', '#111214'], ['#2b2d31', '#111214']],
    shapes: ['circle', 'roundedSquare', 'badge'],
    reason: 'a ghost on Halloween orange and black',
  },
  {
    id: 'magic',
    label: 'Wizard',
    keywords: ['magic', 'magical', 'magician', 'wizard', 'wizards', 'mage', 'sorcerer', 'sorceress', 'witchcraft', 'spell', 'spells', 'enchanted', 'enchanter', 'mystic', 'mystical', 'fortune', 'oracle', 'psychic', 'crystal', 'fairy', 'fae', 'unicorn', 'unicorns', 'fantasy', 'dnd', 'dungeon', 'dungeons', 'dragons', 'rpg', 'tabletop', 'dm', 'gm'],
    emoji: ['🧙', '🪄', '🔮', '✨', '🦄', '🐉', '🎲'],
    symbols: ['moon', 'star'],
    palettes: [['#9b59b6', '#71368a'], ['#7d3cff', '#0f2a44'], ['#e91e63', '#71368a']],
    shapes: ['circle', 'star', 'hexagon'],
    reason: 'a crystal ball in mystic purple',
  },
  {
    id: 'food',
    label: 'Foodie',
    keywords: ['food', 'foodie', 'chef', 'cook', 'cooking', 'kitchen', 'baker', 'baking', 'recipe', 'recipes', 'snack', 'snacks', 'hungry', 'eat', 'eating', 'restaurant', 'dinner', 'lunch', 'breakfast'],
    emoji: ['🍕', '🍔', '🍳', '🧁', '🍜', '🍩'],
    symbols: [],
    palettes: [['#e67e22', '#e74c3c'], ['#f1c40f', '#e67e22'], ['#e91e63', '#e67e22']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a pizza slice on warm colors',
  },
  {
    id: 'coffee',
    label: 'Coffee Club',
    keywords: ['coffee', 'cafe', 'café', 'barista', 'caffeine', 'espresso', 'latte', 'tea', 'boba', 'bubble tea', 'cozy', 'cosy', 'comfy', 'chill', 'chilled', 'relax', 'relaxed', 'lounge', 'lofi', 'lo-fi', 'calm', 'zen'],
    emoji: ['☕', '🧋', '🍵', '🍂', '🛋️'],
    symbols: [],
    palettes: [['#e67e22', '#a84300'], ['#c27c0e', '#5c3a21'], ['#d2b48c', '#8d5a3b']],
    shapes: ['circle', 'roundedSquare', 'squircle'],
    reason: 'a warm cup on cozy browns',
  },
  {
    id: 'sports',
    label: 'Athlete',
    keywords: ['sport', 'sports', 'athlete', 'athletes', 'soccer', 'football', 'basketball', 'baseball', 'tennis', 'volleyball', 'hockey', 'golf', 'rugby', 'cricket', 'boxing', 'boxer', 'mma', 'wrestling', 'wrestler', 'fitness', 'gym', 'workout', 'lifting', 'runner', 'running', 'marathon', 'cycling', 'cyclist', 'skate', 'skater', 'skateboard', 'coach', 'captain'],
    emoji: ['⚽', '🏀', '🏈', '⚾', '🎾', '🥊', '💪', '🏃'],
    symbols: ['trophy', 'star'],
    palettes: [['#e74c3c', '#992d22'], ['#3498db', '#206694'], ['#2ecc71', '#1f8b4c']],
    shapes: ['circle', 'shield', 'hexagon'],
    reason: 'a ball on a team-crest shield',
  },
  {
    id: 'photo',
    label: 'Photographer',
    keywords: ['photo', 'photos', 'photographer', 'photography', 'camera', 'picture', 'pictures', 'pic', 'pics', 'snapshot', 'film', 'filmmaker', 'movie', 'movies', 'cinema', 'director', 'editor', 'editing', 'video', 'videos', 'videographer', 'clip', 'clips'],
    emoji: ['📷', '📸', '🎬', '🎥', '🎞️'],
    symbols: [],
    palettes: [['#2b2d31', '#111214'], ['#95a5a6', '#546e7a'], ['#e91e63', '#71368a']],
    shapes: ['roundedSquare', 'circle'],
    contentColor: '#f2f3f5',
    reason: 'a camera on a dark tile',
  },
  {
    id: 'voice',
    label: 'Voice',
    keywords: ['voice', 'vc', 'talk', 'talker', 'talkative', 'chat', 'chatter', 'chatty', 'speaker', 'mic', 'microphone', 'podcast', 'podcaster', 'radio', 'announcer', 'announcement', 'announcements', 'news', 'reporter', 'journalist', 'caller', 'yapper', 'loud', 'megaphone', 'shout'],
    emoji: ['🎙️', '📣', '🔊', '📻', '🗣️', '💬'],
    symbols: ['note'],
    palettes: [['#3498db', '#206694'], ['#e67e22', '#a84300'], ['#9b59b6', '#71368a']],
    shapes: ['circle', 'roundedSquare'],
    reason: 'a microphone',
  },
  {
    id: 'writer',
    label: 'Writer',
    keywords: ['writer', 'writers', 'writing', 'write', 'author', 'authors', 'poet', 'poetry', 'poem', 'story', 'stories', 'storyteller', 'novel', 'novelist', 'roleplay', 'roleplayer', 'rp', 'lore', 'loremaster', 'scribe', 'blogger', 'blog', 'journal', 'notes'],
    emoji: ['✍️', '📝', '🖋️', '📜', '📖'],
    symbols: [],
    palettes: [['#546e7a', '#2b2d31'], ['#e67e22', '#a84300'], ['#9b59b6', '#71368a']],
    shapes: ['circle', 'roundedSquare', 'badge'],
    reason: 'a pen and scroll',
  },
  {
    id: 'meme',
    label: 'Meme Lord',
    keywords: ['meme', 'memes', 'memer', 'funny', 'comedian', 'comedy', 'joke', 'jokes', 'joker', 'clown', 'clowns', 'laugh', 'laughing', 'humor', 'humour', 'shitpost', 'shitposter', 'goofy', 'silly', 'troll', 'trolls', 'chaos', 'chaotic', 'gremlin', 'goblin'],
    emoji: ['😂', '🤣', '🤡', '💀', '🗿', '🤪'],
    symbols: [],
    palettes: [['#f1c40f', '#e67e22'], ['#e91e63', '#9b59b6'], ['#2ecc71', '#3498db']],
    shapes: ['circle', 'roundedSquare', 'squircle'],
    reason: 'a laughing face, because that is the job',
  },
  {
    id: 'angel',
    label: 'Angel',
    keywords: ['angel', 'angels', 'angelic', 'holy', 'heaven', 'heavenly', 'saint', 'blessed', 'divine', 'halo', 'pure', 'innocent', 'faith', 'church', 'pray', 'prayer', 'peace', 'peaceful', 'gentle'],
    emoji: ['😇', '👼', '🕊️', '🙏', '☮️'],
    symbols: ['star', 'heart'],
    palettes: [['#f2f3f5', '#c0c7cc'], ['#ffd166', '#f2f3f5'], ['#a8e6ff', '#f2f3f5']],
    shapes: ['circle', 'badge'],
    contentColor: '#f1c40f',
    reason: 'a halo on soft white',
  },
  {
    id: 'detective',
    label: 'Detective',
    keywords: ['detective', 'detectives', 'investigator', 'mystery', 'sleuth', 'spy', 'spies', 'agent', 'agents', 'secret agent', 'lurker', 'lurkers', 'lurk', 'lurking', 'watcher', 'watchers', 'observer', 'stalker', 'ghost mode', 'incognito', 'anonymous', 'anon', 'stealth'],
    emoji: ['🕵️', '👀', '👁️', '🔍', '🥷'],
    symbols: ['moon'],
    palettes: [['#546e7a', '#2b2d31'], ['#2b2d31', '#111214'], ['#71368a', '#111214']],
    shapes: ['circle', 'roundedSquare'],
    contentColor: '#f2f3f5',
    reason: 'a detective on a shadowy gray',
  },
  {
    id: 'medic',
    label: 'Medic',
    keywords: ['medic', 'medical', 'doctor', 'doctors', 'nurse', 'nurses', 'health', 'healer', 'healers', 'heal', 'healing', 'hospital', 'first aid', 'therapist', 'therapy', 'counselor', 'counsellor', 'wellness', 'mental health', 'listener', 'listeners', 'helpline', 'safe'],
    emoji: ['🩺', '💊', '🩹', '❤️‍🩹', '🧑‍⚕️'],
    symbols: ['heart', 'check'],
    palettes: [['#e74c3c', '#f2f3f5'], ['#1abc9c', '#11806a'], ['#3498db', '#206694']],
    shapes: ['circle', 'badge', 'roundedSquare'],
    reason: 'a stethoscope, calm and caring',
  },
  {
    id: 'cowboy',
    label: 'Cowboy',
    keywords: ['cowboy', 'cowboys', 'cowgirl', 'western', 'ranch', 'rancher', 'rodeo', 'wild west', 'yeehaw', 'texas', 'country', 'horse', 'horses', 'saloon'],
    emoji: ['🤠', '🐴', '🌵', '🐎'],
    symbols: ['star'],
    palettes: [['#e67e22', '#a84300'], ['#c27c0e', '#5c3a21'], ['#f1c40f', '#e67e22']],
    shapes: ['circle', 'badge', 'shield'],
    reason: 'a cowboy hat and a sheriff star',
  },
];

/** Nouns that map straight to emoji, when nothing above fits better. */
export const EMOJI_WORDS: Readonly<Record<string, readonly string[]>> = {
  dog: ['🐶', '🐕'], puppy: ['🐶'], pup: ['🐶'], doggo: ['🐶'], cat: ['🐱', '🐈'], kitten: ['🐱'], kitty: ['🐱'],
  mouse: ['🐭'], hamster: ['🐹'], bunny: ['🐰'], rabbit: ['🐰'], fox: ['🦊'], bear: ['🐻'], panda: ['🐼'], koala: ['🐨'],
  tiger: ['🐯'], lion: ['🦁'], cow: ['🐮'], pig: ['🐷'], frog: ['🐸'], monkey: ['🐵'], chicken: ['🐔'], penguin: ['🐧'],
  bird: ['🐦'], duck: ['🦆'], eagle: ['🦅'], owl: ['🦉'], bat: ['🦇'], wolf: ['🐺'], boar: ['🐗'], horse: ['🐴'],
  unicorn: ['🦄'], bee: ['🐝'], butterfly: ['🦋'], snail: ['🐌'], turtle: ['🐢'], snake: ['🐍'], octopus: ['🐙'],
  shark: ['🦈'], dolphin: ['🐬'], whale: ['🐳'], dragon: ['🐉', '🐲'], dino: ['🦖'], dinosaur: ['🦖'], trex: ['🦖'],
  crab: ['🦀'], lobster: ['🦞'], shrimp: ['🦐'], squid: ['🦑'], parrot: ['🦜'], flamingo: ['🦩'], peacock: ['🦚'],
  sloth: ['🦥'], otter: ['🦦'], raccoon: ['🦝'], deer: ['🦌'], goat: ['🐐'], sheep: ['🐑'], llama: ['🦙'], camel: ['🐫'],
  elephant: ['🐘'], rhino: ['🦏'], hippo: ['🦛'], gorilla: ['🦍'], giraffe: ['🦒'], zebra: ['🦓'], kangaroo: ['🦘'],
  spider: ['🕷️'], scorpion: ['🦂'], ant: ['🐜'], ladybug: ['🐞'], cricket: ['🦗'], mosquito: ['🦟'], worm: ['🪱'],
  pizza: ['🍕'], burger: ['🍔'], hamburger: ['🍔'], fries: ['🍟'], taco: ['🌮'], burrito: ['🌯'], sushi: ['🍣'],
  ramen: ['🍜'], noodle: ['🍜'], noodles: ['🍜'], rice: ['🍚'], bread: ['🍞'], croissant: ['🥐'], pretzel: ['🥨'],
  donut: ['🍩'], doughnut: ['🍩'], cookie: ['🍪'], cake: ['🎂', '🍰'], cupcake: ['🧁'], pie: ['🥧'], chocolate: ['🍫'],
  candy: ['🍬', '🍭'], lollipop: ['🍭'], icecream: ['🍦'], popcorn: ['🍿'], egg: ['🥚'], bacon: ['🥓'], cheese: ['🧀'],
  apple: ['🍎'], banana: ['🍌'], strawberry: ['🍓'], cherry: ['🍒'], cherries: ['🍒'], grape: ['🍇'], grapes: ['🍇'],
  watermelon: ['🍉'], lemon: ['🍋'], orange: ['🍊'], peach: ['🍑'], mango: ['🥭'], pineapple: ['🍍'], coconut: ['🥥'],
  avocado: ['🥑'], pepper: ['🌶️'], chili: ['🌶️'], mushroom: ['🍄'], carrot: ['🥕'], corn: ['🌽'], potato: ['🥔'],
  beer: ['🍺'], wine: ['🍷'], cocktail: ['🍸'], milk: ['🥛'], juice: ['🧃'], soda: ['🥤'],
  rocket: ['🚀'], plane: ['✈️'], airplane: ['✈️'], pilot: ['✈️'], car: ['🚗'], racing: ['🏎️'], racer: ['🏎️'],
  driver: ['🚗'], truck: ['🚚'], bus: ['🚌'], train: ['🚂'], bike: ['🚲'], motorcycle: ['🏍️'], boat: ['⛵'],
  ship: ['🚢'], anchor: ['⚓'], helicopter: ['🚁'], satellite: ['📡'], phone: ['📱'], laptop: ['💻'], keyboard: ['⌨️'],
  tv: ['📺'], television: ['📺'], radio: ['📻'], headphones: ['🎧'], headset: ['🎧'], guitar: ['🎸'], piano: ['🎹'],
  drum: ['🥁'], drums: ['🥁'], trumpet: ['🎺'], violin: ['🎻'], saxophone: ['🎷'], dice: ['🎲'], chess: ['♟️'],
  puzzle: ['🧩'], cards: ['🃏'], poker: ['🃏'], joker: ['🃏'], darts: ['🎯'], target: ['🎯'], bowling: ['🎳'],
  bomb: ['💣'], boom: ['💥'], explosion: ['💥'], dynamite: ['🧨'], gun: ['🔫'], shooter: ['🔫'], fps: ['🔫'],
  bow: ['🏹'], archer: ['🏹'], archery: ['🏹'], axe: ['🪓'], hammer: ['🔨'], wrench: ['🔧'], tools: ['🛠️'],
  magnet: ['🧲'], bulb: ['💡'], lightbulb: ['💡'], idea: ['💡'], ideas: ['💡'], inventor: ['💡'], flashlight: ['🔦'],
  telescope: ['🔭'], astronomy: ['🔭'], microscope: ['🔬'], compass: ['🧭'], map: ['🗺️'], pin: ['📍'], globe: ['🌍'],
  world: ['🌍'], global: ['🌍'], clock: ['⏰'], timer: ['⏱️'], hourglass: ['⏳'], calendar: ['📅'],
  bell: ['🔔'], alarm: ['🚨'], siren: ['🚨'], warning: ['⚠️'], caution: ['⚠️'], stop: ['🛑'], flag: ['🚩'],
  gift: ['🎁'], present: ['🎁'], balloon: ['🎈'], ticket: ['🎟️'], tickets: ['🎟️'], mask: ['🎭'], theater: ['🎭'],
  theatre: ['🎭'], drama: ['🎭'], actor: ['🎭'], palette: ['🎨'], brush: ['🖌️'], pencil: ['✏️'], pen: ['🖊️'],
  scissors: ['✂️'], barber: ['✂️'], needle: ['🪡'], thread: ['🧵'], sewing: ['🧵'], tailor: ['🧵'], knitting: ['🧶'],
  yarn: ['🧶'], crown: ['👑'], gem: ['💎'], diamond: ['💎'], jewel: ['💎'], gold: ['🥇'],
  trophy: ['🏆'], medal: ['🏅'], ribbon: ['🎀'], hat: ['🎩'], tophat: ['🎩'], cap: ['🧢'],
  glasses: ['👓'], sunglasses: ['🕶️'], shirt: ['👕'], dress: ['👗'], shoe: ['👟'], sneaker: ['👟'], boot: ['🥾'],
  umbrella: ['☂️'], rain: ['🌧️'], rainy: ['🌧️'], cloud: ['☁️'], clouds: ['☁️'], sun: ['☀️'], sunny: ['☀️'],
  summer: ['☀️', '🌴'], rainbow: ['🌈'], pride: ['🏳️‍🌈'], lgbt: ['🏳️‍🌈'], lgbtq: ['🏳️‍🌈'], tornado: ['🌪️'],
  volcano: ['🌋'], mountain: ['⛰️'], mountains: ['🏔️'], desert: ['🌵'], cactus: ['🌵'], palm: ['🌴'],
  tropical: ['🌴'], sunflower: ['🌻'], rose: ['🌹'], tulip: ['🌷'], clover: ['🍀'], lucky: ['🍀'], luck: ['🍀'],
  irish: ['🍀'], shamrock: ['☘️'], herb: ['🌿'], bamboo: ['🎋'], mushrooms: ['🍄'], seedling: ['🌱'],
  ghost: ['👻'], pumpkin: ['🎃'], alien: ['👽'], ufo: ['🛸'], robot: ['🤖'], zombie: ['🧟'], vampire: ['🧛'],
  mermaid: ['🧜'], genie: ['🧞'], elf: ['🧝'], fairy: ['🧚'], superhero: ['🦸'], supervillain: ['🦹'], ninja: ['🥷'],
  pirate: ['🏴‍☠️'], santa: ['🎅'], snowman: ['⛄'], baby: ['👶'], skull: ['💀'], bone: ['🦴'], eye: ['👁️'],
  eyes: ['👀'], brain: ['🧠'], muscle: ['💪'], flex: ['💪'], hello: ['👋'], hi: ['👋'],
  clap: ['👏'], applause: ['👏'], thumbs: ['👍'], like: ['👍'], fist: ['✊'], punch: ['👊'], handshake: ['🤝'],
  deal: ['🤝'], collab: ['🤝'], collaboration: ['🤝'], salute: ['🫡'], point: ['👉'], ok: ['👌'], rock: ['🤘'],
  horns: ['🤘'], vulcan: ['🖖'], trek: ['🖖'], lips: ['👄'], tongue: ['👅'], ear: ['👂'], nose: ['👃'],
  footprints: ['👣'], poop: ['💩'], hundred: ['💯'], perfect: ['💯'], sparkle: ['✨'],
  sparkles: ['✨'], glitter: ['✨'], comet: ['☄️'], meteor: ['☄️'], zzz: ['💤'],
  smile: ['😀'], happy: ['😊'], joy: ['😄'], smiley: ['🙂'], sunglass: ['😎'], nerdy: ['🤓'],
  monocle: ['🧐'], thinking: ['🤔'], thinker: ['🤔'], hmm: ['🤔'], shush: ['🤫'],
  quiet: ['🤫'], sad: ['😢'], crying: ['😭'], cry: ['😭'], angry: ['😡'], rage: ['😡'], mad: ['😡'], sick: ['🤒'],
  sleeping: ['😴'], tired: ['😴'], dizzy: ['😵'], mindblown: ['🤯'], scream: ['😱'], shocked: ['😲'],
  wink: ['😉'], flirt: ['😉'], kiss: ['😘'], hugging: ['🤗'], hugger: ['🤗'], party: ['🥳'], starstruck: ['🤩'],
  drool: ['🤤'], lying: ['🤥'], liar: ['🤥'], disguise: ['🥸'],
  melting: ['🫠'], sunshine: ['🌞'], usa: ['🇺🇸'], america: ['🇺🇸'], american: ['🇺🇸'],
  uk: ['🇬🇧'], britain: ['🇬🇧'], british: ['🇬🇧'], england: ['🇬🇧'], english: ['🇬🇧'], japan: ['🇯🇵'],
  japanese: ['🇯🇵'], korea: ['🇰🇷'], korean: ['🇰🇷'], brazil: ['🇧🇷'], brazilian: ['🇧🇷'], germany: ['🇩🇪'],
  german: ['🇩🇪'], france: ['🇫🇷'], french: ['🇫🇷'], spain: ['🇪🇸'], spanish: ['🇪🇸'], canada: ['🇨🇦'],
  canadian: ['🇨🇦'], australia: ['🇦🇺'], australian: ['🇦🇺'], aussie: ['🇦🇺'], vietnam: ['🇻🇳'], vietnamese: ['🇻🇳'],
  viet: ['🇻🇳'], india: ['🇮🇳'], indian: ['🇮🇳'], mexico: ['🇲🇽'], mexican: ['🇲🇽'], italy: ['🇮🇹'], italian: ['🇮🇹'],
  china: ['🇨🇳'], chinese: ['🇨🇳'], russia: ['🇷🇺'], russian: ['🇷🇺'], philippines: ['🇵🇭'], filipino: ['🇵🇭'],
  pinoy: ['🇵🇭'], indonesia: ['🇮🇩'], indonesian: ['🇮🇩'], turkey: ['🇹🇷'], turkish: ['🇹🇷'], poland: ['🇵🇱'],
  polish: ['🇵🇱'], netherlands: ['🇳🇱'], dutch: ['🇳🇱'], sweden: ['🇸🇪'], swedish: ['🇸🇪'], norway: ['🇳🇴'],
  norwegian: ['🇳🇴'], ukraine: ['🇺🇦'], ukrainian: ['🇺🇦'], argentina: ['🇦🇷'], portugal: ['🇵🇹'],
  portuguese: ['🇵🇹'], thailand: ['🇹🇭'], thai: ['🇹🇭'], malaysia: ['🇲🇾'], singapore: ['🇸🇬'], europe: ['🇪🇺'],
  european: ['🇪🇺'], checkered: ['🏁'], finish: ['🏁'],
};

export const STYLES: readonly Style[] = [
  {
    id: 'cute',
    label: 'cute',
    keywords: ['cute', 'cuter', 'kawaii', 'adorable', 'soft', 'pastel', 'sweet', 'lovely', 'uwu', 'cutesy', 'aesthetic'],
    palettes: [['#ffb3d9', '#ff73fa'], ['#c8a2ff', '#9b59b6'], ['#a8e6ff', '#3498db'], ['#ffd6a5', '#ff9e7a']],
    shapes: ['circle', 'heart', 'roundedSquare', 'squircle'],
    gloss: true,
    border: true,
    prefer: 'emoji',
  },
  {
    id: 'bold',
    label: 'bold',
    keywords: ['bold', 'bolder', 'strong', 'heavy', 'chunky', 'sturdy', 'tough', 'hardcore', 'brutal', 'aggressive', 'intense'],
    shapes: ['hexagon', 'square', 'shield'],
    fillType: 'linear',
    border: true,
    prefer: 'symbol',
  },
  {
    id: 'dark',
    label: 'dark',
    keywords: ['dark', 'edgy', 'gothic', 'moody', 'gloomy', 'grim', 'sinister', 'shadowy', 'noir', 'blackout'],
    palettes: [['#2b2d31', '#111214'], ['#3f4147', '#1e1f22'], ['#4a0d0d', '#1a0505'], ['#1b1b3a', '#0b0b1a']],
    shadow: true,
    contentColor: '#f2f3f5',
  },
  {
    id: 'neon',
    label: 'neon',
    keywords: ['neon', 'cyber', 'cyberpunk', 'glow', 'glowing', 'synthwave', 'vaporwave', 'futuristic', 'future', 'sci-fi', 'scifi', 'techno', 'electric', 'laser', 'holo', 'holographic', 'rgb'],
    palettes: [['#00f0ff', '#7a00ff'], ['#ff00c8', '#7a00ff'], ['#39ff14', '#00b3ff'], ['#ff2079', '#0f0f2d']],
    shapes: ['hexagon', 'roundedSquare', 'circle'],
    glow: true,
    border: false,
  },
  {
    id: 'minimal',
    label: 'minimal',
    keywords: ['minimal', 'minimalist', 'simple', 'simpler', 'cleaner', 'clean', 'flat', 'plain', 'basic', 'subtle', 'understated', 'modern', 'sleek'],
    fillType: 'solid',
    border: false,
    gloss: false,
    shadow: false,
    prefer: 'symbol',
  },
  {
    id: 'fancy',
    label: 'fancy',
    keywords: ['fancy', 'fancier', 'elegant', 'royal', 'luxury', 'luxurious', 'premium', 'rich', 'classy', 'posh', 'regal', 'majestic', 'noble', 'prestige', 'prestigious', 'golden', 'glam', 'glamorous', 'bling'],
    palettes: [['#f1c40f', '#e67e22'], ['#ffd166', '#c27c0e'], ['#f9e79f', '#c27c0e']],
    shapes: ['badge', 'shield', 'circle'],
    gloss: true,
    border: true,
  },
  {
    id: 'retro',
    label: 'retro',
    keywords: ['retro', 'pixel', 'pixelated', '8bit', '8-bit', 'arcade', 'vintage', 'oldschool', 'old-school', 'classic', 'nostalgic', '90s', '80s'],
    palettes: [['#ff6b6b', '#ffd93d'], ['#4ecdc4', '#1a535c'], ['#ff9f1c', '#2ec4b6']],
    shapes: ['square', 'roundedSquare'],
    font: 'pressstart',
    fillType: 'solid',
    border: true,
  },
  {
    id: 'fun',
    label: 'fun',
    keywords: ['fun', 'playful', 'happy', 'cheerful', 'bright', 'colorful', 'colourful', 'vibrant', 'lively', 'bubbly', 'joyful', 'wacky', 'zany', 'quirky', 'cartoon', 'cartoony', 'comic'],
    palettes: [['#ff6b6b', '#feca57'], ['#48dbfb', '#ff9ff3'], ['#1dd1a1', '#feca57'], ['#ff9ff3', '#54a0ff']],
    fillType: 'radial',
    prefer: 'emoji',
    font: 'bangers',
  },
  {
    id: 'professional',
    label: 'professional',
    keywords: ['professional', 'serious', 'corporate', 'business', 'formal', 'official', 'proper', 'mature', 'grown', 'work', 'enterprise'],
    palettes: [['#3498db', '#206694'], ['#546e7a', '#2b2d31'], ['#1f3b6f', '#0f2a44']],
    shapes: ['roundedSquare', 'circle', 'square'],
    fillType: 'solid',
    border: false,
    gloss: false,
    prefer: 'symbol',
  },
  {
    id: 'nature',
    label: 'natural',
    keywords: ['earthy', 'organic', 'botanical', 'rustic', 'woodland'],
    palettes: [['#2ecc71', '#1f8b4c'], ['#8d5a3b', '#5c3a21'], ['#7a8b2b', '#1f5f3a']],
    shapes: ['circle', 'roundedSquare'],
  },
  {
    id: 'ice',
    label: 'icy',
    keywords: ['icy', 'frosty', 'crystal', 'glacial', 'cool-toned', 'wintry'],
    palettes: [['#a8e6ff', '#3498db'], ['#e0f7ff', '#5dc7ff']],
    contentColor: '#0f2a44',
  },
  {
    id: 'galaxy',
    label: 'galactic',
    keywords: ['galactic', 'starry', 'celestial', 'astral', 'ethereal', 'dreamy', 'aurora'],
    palettes: [['#7d3cff', '#0f2a44'], ['#e91e63', '#206694'], ['#00d4ff', '#7d3cff']],
    shapes: ['circle', 'hexagon'],
    fillType: 'linear',
    glow: true,
  },
  {
    id: 'shiny',
    label: 'glossy',
    keywords: ['glossy', 'shiny', 'shine', 'polished', 'gleaming', 'glass', 'glassy', 'bubbly', 'candy', 'jelly'],
    gloss: true,
    border: true,
    fillType: 'linear',
  },
];

/** Used when the prompt mentions nothing we recognise. */
export const GENERIC_PALETTES: readonly Palette[] = [
  ['#3498db', '#206694'],
  ['#2ecc71', '#1f8b4c'],
  ['#9b59b6', '#71368a'],
  ['#e67e22', '#a84300'],
  ['#e91e63', '#ad1457'],
  ['#1abc9c', '#11806a'],
];

export const GENERIC_SHAPES: readonly ShapeKind[] = ['circle', 'roundedSquare', 'hexagon', 'badge', 'shield', 'squircle'];

export const GENERIC_EMOJI: readonly string[] = ['⭐', '🔥', '💎', '⚡', '🚀', '🌟'];
export const GENERIC_SYMBOLS: readonly SymbolId[] = ['star', 'bolt', 'gem', 'crown'];

export const STOP_WORDS: ReadonlySet<string> = new Set([
  'a', 'an', 'the', 'and', 'or', 'for', 'with', 'of', 'to', 'in', 'on', 'at', 'is', 'it', 'its', 'my', 'our', 'me',
  'i', 'we', 'you', 'us', 'want', 'wants', 'need', 'like', 'make', 'create', 'give', 'design', 'something', 'some',
  'icon', 'icons', 'logo', 'logos', 'role', 'roles', 'please', 'pls', 'plz', 'that', 'this', 'be', 'looks', 'look',
  'looking', 'kind', 'sort', 'type', 'server', 'discord', 'channel', 'people', 'who', 'are', 'can', 'should', 'would',
  'them', 'they', 'their', 'so', 'but', 'very', 'really', 'super', 'just', 'one', 'have', 'has', 'get', 'idea', 'ideas',
  'do', 'does', 'from', 'by', 'as', 'about', 'into', 'up', 'out', 'if', 'then', 'than', 'what', 'which',
]);
